DROP TABLE board IF EXISTS;

CREATE TABLE board (
    seq INTEGER NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(1000) NOT NULL,
    writer VARCHAR(10) NOT NULL,
    password INTEGER NOT NULL,
    regDate TIMESTAMP NOT NULL ,
    count INTEGER NOT NULL,
    PRIMARY KEY (seq)
);